/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ReportRouteImport } from './routes/report'
import { Route as AnalyzingRouteImport } from './routes/analyzing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportIndexRouteImport } from './routes/report.index'
import { Route as ReportTransactionsSummaryRouteImport } from './routes/report.transactions-summary'
import { Route as ReportTradeDebitsRouteImport } from './routes/report.trade-debits'
import { Route as ReportTradeCreditsRouteImport } from './routes/report.trade-credits'
import { Route as ReportStaffRouteImport } from './routes/report.staff'
import { Route as ReportSpendRouteImport } from './routes/report.spend'
import { Route as ReportSalaryRouteImport } from './routes/report.salary'
import { Route as ReportRecurringDebitRouteImport } from './routes/report.recurring-debit'
import { Route as ReportRecurringCreditRouteImport } from './routes/report.recurring-credit'
import { Route as ReportOverviewRouteImport } from './routes/report.overview'
import { Route as ReportNetRouteImport } from './routes/report.net'
import { Route as ReportMomRouteImport } from './routes/report.mom'
import { Route as ReportLoansRouteImport } from './routes/report.loans'
import { Route as ReportInternalRouteImport } from './routes/report.internal'
import { Route as ReportHighestRouteImport } from './routes/report.highest'
import { Route as ReportFlagsRouteImport } from './routes/report.flags'
import { Route as ReportEmiTrackerRouteImport } from './routes/report.emi-tracker'
import { Route as ReportCircularRouteImport } from './routes/report.circular'
import { Route as ReportCashflowRouteImport } from './routes/report.cashflow'
import { Route as ReportCamRouteImport } from './routes/report.cam'
import { Route as ReportBounceRouteImport } from './routes/report.bounce'
import { Route as ReportBillsRouteImport } from './routes/report.bills'
import { Route as PrintMasterRouteImport } from './routes/print.master'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzingRoute = AnalyzingRouteImport.update({
  id: '/analyzing',
  path: '/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportRoute,
} as any)
const ReportTransactionsSummaryRoute =
  ReportTransactionsSummaryRouteImport.update({
    id: '/transactions-summary',
    path: '/transactions-summary',
    getParentRoute: () => ReportRoute,
  } as any)
const ReportTradeDebitsRoute = ReportTradeDebitsRouteImport.update({
  id: '/trade-debits',
  path: '/trade-debits',
  getParentRoute: () => ReportRoute,
} as any)
const ReportTradeCreditsRoute = ReportTradeCreditsRouteImport.update({
  id: '/trade-credits',
  path: '/trade-credits',
  getParentRoute: () => ReportRoute,
} as any)
const ReportStaffRoute = ReportStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ReportRoute,
} as any)
const ReportSpendRoute = ReportSpendRouteImport.update({
  id: '/spend',
  path: '/spend',
  getParentRoute: () => ReportRoute,
} as any)
const ReportSalaryRoute = ReportSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => ReportRoute,
} as any)
const ReportRecurringDebitRoute = ReportRecurringDebitRouteImport.update({
  id: '/recurring-debit',
  path: '/recurring-debit',
  getParentRoute: () => ReportRoute,
} as any)
const ReportRecurringCreditRoute = ReportRecurringCreditRouteImport.update({
  id: '/recurring-credit',
  path: '/recurring-credit',
  getParentRoute: () => ReportRoute,
} as any)
const ReportOverviewRoute = ReportOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ReportRoute,
} as any)
const ReportNetRoute = ReportNetRouteImport.update({
  id: '/net',
  path: '/net',
  getParentRoute: () => ReportRoute,
} as any)
const ReportMomRoute = ReportMomRouteImport.update({
  id: '/mom',
  path: '/mom',
  getParentRoute: () => ReportRoute,
} as any)
const ReportLoansRoute = ReportLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => ReportRoute,
} as any)
const ReportInternalRoute = ReportInternalRouteImport.update({
  id: '/internal',
  path: '/internal',
  getParentRoute: () => ReportRoute,
} as any)
const ReportHighestRoute = ReportHighestRouteImport.update({
  id: '/highest',
  path: '/highest',
  getParentRoute: () => ReportRoute,
} as any)
const ReportFlagsRoute = ReportFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => ReportRoute,
} as any)
const ReportEmiTrackerRoute = ReportEmiTrackerRouteImport.update({
  id: '/emi-tracker',
  path: '/emi-tracker',
  getParentRoute: () => ReportRoute,
} as any)
const ReportCircularRoute = ReportCircularRouteImport.update({
  id: '/circular',
  path: '/circular',
  getParentRoute: () => ReportRoute,
} as any)
const ReportCashflowRoute = ReportCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => ReportRoute,
} as any)
const ReportCamRoute = ReportCamRouteImport.update({
  id: '/cam',
  path: '/cam',
  getParentRoute: () => ReportRoute,
} as any)
const ReportBounceRoute = ReportBounceRouteImport.update({
  id: '/bounce',
  path: '/bounce',
  getParentRoute: () => ReportRoute,
} as any)
const ReportBillsRoute = ReportBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => ReportRoute,
} as any)
const PrintMasterRoute = PrintMasterRouteImport.update({
  id: '/print/master',
  path: '/print/master',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyzing': typeof AnalyzingRoute
  '/report': typeof ReportRouteWithChildren
  '/upload': typeof UploadRoute
  '/print/master': typeof PrintMasterRoute
  '/report/bills': typeof ReportBillsRoute
  '/report/bounce': typeof ReportBounceRoute
  '/report/cam': typeof ReportCamRoute
  '/report/cashflow': typeof ReportCashflowRoute
  '/report/circular': typeof ReportCircularRoute
  '/report/emi-tracker': typeof ReportEmiTrackerRoute
  '/report/flags': typeof ReportFlagsRoute
  '/report/highest': typeof ReportHighestRoute
  '/report/internal': typeof ReportInternalRoute
  '/report/loans': typeof ReportLoansRoute
  '/report/mom': typeof ReportMomRoute
  '/report/net': typeof ReportNetRoute
  '/report/overview': typeof ReportOverviewRoute
  '/report/recurring-credit': typeof ReportRecurringCreditRoute
  '/report/recurring-debit': typeof ReportRecurringDebitRoute
  '/report/salary': typeof ReportSalaryRoute
  '/report/spend': typeof ReportSpendRoute
  '/report/staff': typeof ReportStaffRoute
  '/report/trade-credits': typeof ReportTradeCreditsRoute
  '/report/trade-debits': typeof ReportTradeDebitsRoute
  '/report/transactions-summary': typeof ReportTransactionsSummaryRoute
  '/report/': typeof ReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyzing': typeof AnalyzingRoute
  '/upload': typeof UploadRoute
  '/print/master': typeof PrintMasterRoute
  '/report/bills': typeof ReportBillsRoute
  '/report/bounce': typeof ReportBounceRoute
  '/report/cam': typeof ReportCamRoute
  '/report/cashflow': typeof ReportCashflowRoute
  '/report/circular': typeof ReportCircularRoute
  '/report/emi-tracker': typeof ReportEmiTrackerRoute
  '/report/flags': typeof ReportFlagsRoute
  '/report/highest': typeof ReportHighestRoute
  '/report/internal': typeof ReportInternalRoute
  '/report/loans': typeof ReportLoansRoute
  '/report/mom': typeof ReportMomRoute
  '/report/net': typeof ReportNetRoute
  '/report/overview': typeof ReportOverviewRoute
  '/report/recurring-credit': typeof ReportRecurringCreditRoute
  '/report/recurring-debit': typeof ReportRecurringDebitRoute
  '/report/salary': typeof ReportSalaryRoute
  '/report/spend': typeof ReportSpendRoute
  '/report/staff': typeof ReportStaffRoute
  '/report/trade-credits': typeof ReportTradeCreditsRoute
  '/report/trade-debits': typeof ReportTradeDebitsRoute
  '/report/transactions-summary': typeof ReportTransactionsSummaryRoute
  '/report': typeof ReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyzing': typeof AnalyzingRoute
  '/report': typeof ReportRouteWithChildren
  '/upload': typeof UploadRoute
  '/print/master': typeof PrintMasterRoute
  '/report/bills': typeof ReportBillsRoute
  '/report/bounce': typeof ReportBounceRoute
  '/report/cam': typeof ReportCamRoute
  '/report/cashflow': typeof ReportCashflowRoute
  '/report/circular': typeof ReportCircularRoute
  '/report/emi-tracker': typeof ReportEmiTrackerRoute
  '/report/flags': typeof ReportFlagsRoute
  '/report/highest': typeof ReportHighestRoute
  '/report/internal': typeof ReportInternalRoute
  '/report/loans': typeof ReportLoansRoute
  '/report/mom': typeof ReportMomRoute
  '/report/net': typeof ReportNetRoute
  '/report/overview': typeof ReportOverviewRoute
  '/report/recurring-credit': typeof ReportRecurringCreditRoute
  '/report/recurring-debit': typeof ReportRecurringDebitRoute
  '/report/salary': typeof ReportSalaryRoute
  '/report/spend': typeof ReportSpendRoute
  '/report/staff': typeof ReportStaffRoute
  '/report/trade-credits': typeof ReportTradeCreditsRoute
  '/report/trade-debits': typeof ReportTradeDebitsRoute
  '/report/transactions-summary': typeof ReportTransactionsSummaryRoute
  '/report/': typeof ReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyzing'
    | '/report'
    | '/upload'
    | '/print/master'
    | '/report/bills'
    | '/report/bounce'
    | '/report/cam'
    | '/report/cashflow'
    | '/report/circular'
    | '/report/emi-tracker'
    | '/report/flags'
    | '/report/highest'
    | '/report/internal'
    | '/report/loans'
    | '/report/mom'
    | '/report/net'
    | '/report/overview'
    | '/report/recurring-credit'
    | '/report/recurring-debit'
    | '/report/salary'
    | '/report/spend'
    | '/report/staff'
    | '/report/trade-credits'
    | '/report/trade-debits'
    | '/report/transactions-summary'
    | '/report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyzing'
    | '/upload'
    | '/print/master'
    | '/report/bills'
    | '/report/bounce'
    | '/report/cam'
    | '/report/cashflow'
    | '/report/circular'
    | '/report/emi-tracker'
    | '/report/flags'
    | '/report/highest'
    | '/report/internal'
    | '/report/loans'
    | '/report/mom'
    | '/report/net'
    | '/report/overview'
    | '/report/recurring-credit'
    | '/report/recurring-debit'
    | '/report/salary'
    | '/report/spend'
    | '/report/staff'
    | '/report/trade-credits'
    | '/report/trade-debits'
    | '/report/transactions-summary'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/analyzing'
    | '/report'
    | '/upload'
    | '/print/master'
    | '/report/bills'
    | '/report/bounce'
    | '/report/cam'
    | '/report/cashflow'
    | '/report/circular'
    | '/report/emi-tracker'
    | '/report/flags'
    | '/report/highest'
    | '/report/internal'
    | '/report/loans'
    | '/report/mom'
    | '/report/net'
    | '/report/overview'
    | '/report/recurring-credit'
    | '/report/recurring-debit'
    | '/report/salary'
    | '/report/spend'
    | '/report/staff'
    | '/report/trade-credits'
    | '/report/trade-debits'
    | '/report/transactions-summary'
    | '/report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzingRoute: typeof AnalyzingRoute
  ReportRoute: typeof ReportRouteWithChildren
  UploadRoute: typeof UploadRoute
  PrintMasterRoute: typeof PrintMasterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzing': {
      id: '/analyzing'
      path: '/analyzing'
      fullPath: '/analyzing'
      preLoaderRoute: typeof AnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/': {
      id: '/report/'
      path: '/'
      fullPath: '/report/'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/transactions-summary': {
      id: '/report/transactions-summary'
      path: '/transactions-summary'
      fullPath: '/report/transactions-summary'
      preLoaderRoute: typeof ReportTransactionsSummaryRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/trade-debits': {
      id: '/report/trade-debits'
      path: '/trade-debits'
      fullPath: '/report/trade-debits'
      preLoaderRoute: typeof ReportTradeDebitsRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/trade-credits': {
      id: '/report/trade-credits'
      path: '/trade-credits'
      fullPath: '/report/trade-credits'
      preLoaderRoute: typeof ReportTradeCreditsRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/staff': {
      id: '/report/staff'
      path: '/staff'
      fullPath: '/report/staff'
      preLoaderRoute: typeof ReportStaffRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/spend': {
      id: '/report/spend'
      path: '/spend'
      fullPath: '/report/spend'
      preLoaderRoute: typeof ReportSpendRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/salary': {
      id: '/report/salary'
      path: '/salary'
      fullPath: '/report/salary'
      preLoaderRoute: typeof ReportSalaryRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/recurring-debit': {
      id: '/report/recurring-debit'
      path: '/recurring-debit'
      fullPath: '/report/recurring-debit'
      preLoaderRoute: typeof ReportRecurringDebitRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/recurring-credit': {
      id: '/report/recurring-credit'
      path: '/recurring-credit'
      fullPath: '/report/recurring-credit'
      preLoaderRoute: typeof ReportRecurringCreditRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/overview': {
      id: '/report/overview'
      path: '/overview'
      fullPath: '/report/overview'
      preLoaderRoute: typeof ReportOverviewRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/net': {
      id: '/report/net'
      path: '/net'
      fullPath: '/report/net'
      preLoaderRoute: typeof ReportNetRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/mom': {
      id: '/report/mom'
      path: '/mom'
      fullPath: '/report/mom'
      preLoaderRoute: typeof ReportMomRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/loans': {
      id: '/report/loans'
      path: '/loans'
      fullPath: '/report/loans'
      preLoaderRoute: typeof ReportLoansRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/internal': {
      id: '/report/internal'
      path: '/internal'
      fullPath: '/report/internal'
      preLoaderRoute: typeof ReportInternalRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/highest': {
      id: '/report/highest'
      path: '/highest'
      fullPath: '/report/highest'
      preLoaderRoute: typeof ReportHighestRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/flags': {
      id: '/report/flags'
      path: '/flags'
      fullPath: '/report/flags'
      preLoaderRoute: typeof ReportFlagsRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/emi-tracker': {
      id: '/report/emi-tracker'
      path: '/emi-tracker'
      fullPath: '/report/emi-tracker'
      preLoaderRoute: typeof ReportEmiTrackerRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/circular': {
      id: '/report/circular'
      path: '/circular'
      fullPath: '/report/circular'
      preLoaderRoute: typeof ReportCircularRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/cashflow': {
      id: '/report/cashflow'
      path: '/cashflow'
      fullPath: '/report/cashflow'
      preLoaderRoute: typeof ReportCashflowRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/cam': {
      id: '/report/cam'
      path: '/cam'
      fullPath: '/report/cam'
      preLoaderRoute: typeof ReportCamRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/bounce': {
      id: '/report/bounce'
      path: '/bounce'
      fullPath: '/report/bounce'
      preLoaderRoute: typeof ReportBounceRouteImport
      parentRoute: typeof ReportRoute
    }
    '/report/bills': {
      id: '/report/bills'
      path: '/bills'
      fullPath: '/report/bills'
      preLoaderRoute: typeof ReportBillsRouteImport
      parentRoute: typeof ReportRoute
    }
    '/print/master': {
      id: '/print/master'
      path: '/print/master'
      fullPath: '/print/master'
      preLoaderRoute: typeof PrintMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportRouteChildren {
  ReportBillsRoute: typeof ReportBillsRoute
  ReportBounceRoute: typeof ReportBounceRoute
  ReportCamRoute: typeof ReportCamRoute
  ReportCashflowRoute: typeof ReportCashflowRoute
  ReportCircularRoute: typeof ReportCircularRoute
  ReportEmiTrackerRoute: typeof ReportEmiTrackerRoute
  ReportFlagsRoute: typeof ReportFlagsRoute
  ReportHighestRoute: typeof ReportHighestRoute
  ReportInternalRoute: typeof ReportInternalRoute
  ReportLoansRoute: typeof ReportLoansRoute
  ReportMomRoute: typeof ReportMomRoute
  ReportNetRoute: typeof ReportNetRoute
  ReportOverviewRoute: typeof ReportOverviewRoute
  ReportRecurringCreditRoute: typeof ReportRecurringCreditRoute
  ReportRecurringDebitRoute: typeof ReportRecurringDebitRoute
  ReportSalaryRoute: typeof ReportSalaryRoute
  ReportSpendRoute: typeof ReportSpendRoute
  ReportStaffRoute: typeof ReportStaffRoute
  ReportTradeCreditsRoute: typeof ReportTradeCreditsRoute
  ReportTradeDebitsRoute: typeof ReportTradeDebitsRoute
  ReportTransactionsSummaryRoute: typeof ReportTransactionsSummaryRoute
  ReportIndexRoute: typeof ReportIndexRoute
}

const ReportRouteChildren: ReportRouteChildren = {
  ReportBillsRoute: ReportBillsRoute,
  ReportBounceRoute: ReportBounceRoute,
  ReportCamRoute: ReportCamRoute,
  ReportCashflowRoute: ReportCashflowRoute,
  ReportCircularRoute: ReportCircularRoute,
  ReportEmiTrackerRoute: ReportEmiTrackerRoute,
  ReportFlagsRoute: ReportFlagsRoute,
  ReportHighestRoute: ReportHighestRoute,
  ReportInternalRoute: ReportInternalRoute,
  ReportLoansRoute: ReportLoansRoute,
  ReportMomRoute: ReportMomRoute,
  ReportNetRoute: ReportNetRoute,
  ReportOverviewRoute: ReportOverviewRoute,
  ReportRecurringCreditRoute: ReportRecurringCreditRoute,
  ReportRecurringDebitRoute: ReportRecurringDebitRoute,
  ReportSalaryRoute: ReportSalaryRoute,
  ReportSpendRoute: ReportSpendRoute,
  ReportStaffRoute: ReportStaffRoute,
  ReportTradeCreditsRoute: ReportTradeCreditsRoute,
  ReportTradeDebitsRoute: ReportTradeDebitsRoute,
  ReportTransactionsSummaryRoute: ReportTransactionsSummaryRoute,
  ReportIndexRoute: ReportIndexRoute,
}

const ReportRouteWithChildren =
  ReportRoute._addFileChildren(ReportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzingRoute: AnalyzingRoute,
  ReportRoute: ReportRouteWithChildren,
  UploadRoute: UploadRoute,
  PrintMasterRoute: PrintMasterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
